# python try_except

```

try 블록 수행 중 오류가 발생하면 except블록이 수행된다.
하지만 try 블록에서 오류가 발생하지 않는다면 except블록은 수행되지않는다.

```

```

except[발생 오류[as 오류 메세지 변수]]:

```